# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fallingdust的技术博客
email: fallingdust@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Fallingdust唯一官方技术博客，记录技术上一路走来的点点滴滴
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fallingdust.gitbug.io" # the base hostname & protocol for your site
twitter_username: fallingdust
github_username:  fallingdust

# Build settings
markdown: kramdown
